version: '2'
services:
  mymentor-app:
    image: mymentor
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mymentor-postgresql:5432/mymentor
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://mymentor-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mymentor-elasticsearch:9200
    ports:
      - 8080:8080
  mymentor-postgresql:
    extends:
      file: postgresql.yml
      service: mymentor-postgresql
  mymentor-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mymentor-elasticsearch
